### ISSUE TITLE
about uploading

### ISSUE THREAD

**Issue by Zoesxw** [RSL-NEU/person-reid-benchmark#2]
Thanks for the code! I am doubt whether there are some code not uploaded.

**Comment by NEU-Gou** [comment]
@Zoesxw Thank you for being interested in our code. Could you please be a little bit more specific? Say which function you're missing or what's your error massage?

**Comment by Zoesxw** [comment]
@NEU-Gou For example, folder ./NeuralNet doesn't exist, and about prepare_*.m，only viper and market1501. Is there still some code not uploaded?

**Comment by NEU-Gou** [comment]
@Zoesxw Thanks for the information. 
- Since the fine-tuning code is not ready to share yet, we haven't push that folder yet. 
- For the prepare script, you need to run it ONLY IF there is the corresponding one, which means for DukeMTMC and Airport you just need to unzip and put them under ./Data. I updated README to make it a little bit more clear.
